spring.application.name=jobseeker
server.port=3005

spring.datasource.url=jdbc:mysql://localhost:3306/job_seeker_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
springdoc.swagger-ui.filter=true

spring.jpa.hibernate.ddl-auto=update
